"""Generate the status_vocabulary seed migration from a real attendance workbook.

Reads the 'Summary Report' day-cell values, classifies each into a vocab bucket per SPEC.md §4,
and emits SQL INSERTs. Re-runnable: point --src at any period's workbook to refresh the vocabulary.

Usage:
  python tools/gen_status_vocabulary.py --src "<path to xlsx>" \
      --out supabase/migrations/20260705000003_seed_status_vocabulary.sql
"""
import argparse, re, sys, collections
import openpyxl

# --- classification rules (SPEC §4) --------------------------------------------------------------
SKIP_CLEAN = {
    "normal", "weekend", "public holiday", "not yet hired",
    "present", "no leave", "leave approved", "leave approval",
}
SKIP_LEAVES = {
    "annual leave", "sick leave", "casual leave", "continuing education leave",
    "paternity leave", "bereavement leave", "unpaid leave",
}
NOT_VERIFIED = {"late", "missing punch out", "half day", "halfday", "hlaf day", "2 hour excuse", "excuse"}
TRIGGER_EXACT = {"absent", "no show"}
KNOWN_NOISE = {"#n/a", "0", "departed", "active", "resigned"}
ANNOTATIONS = ("to be confirmed", "to be deducted", "deducted from balance",
               "pending", "failed", "returned", "applied on leave", "- check")


def norm(raw: str) -> str:
    return re.sub(r"\s+", " ", str(raw).strip().lower())


def base_of(n: str) -> str:
    b = re.sub(r"\(.*?\)", "", n)      # drop (HD), (Failed), (Returned) ...
    b = b.split(" - ")[0]             # drop " - Check" / " - To Be deducted ..."
    return re.sub(r"\s+", " ", b).strip()


def classify(raw: str):
    """Return (bucket, canonical_status, note)."""
    n = norm(raw)
    if n == "":
        return None
    is_hd = "(hd)" in n or "half" in base_of(n)
    # 1) explicit mid-dispute / failed annotations win over the base word
    if any(k in n for k in ANNOTATIONS):
        return ("trigger", base_of(n).title() or None, "annotation: unresolved/failed")
    b = base_of(n)
    # 2) genuine unexplained absence
    if b in TRIGGER_EXACT:
        return ("trigger", b.title(), None)
    # 3) clean/resolved
    if b in SKIP_CLEAN or b in SKIP_LEAVES:
        return ("skip", b.title(), "half-day" if is_hd else None)
    # 4) deducts but not verified this stage
    if b in NOT_VERIFIED:
        return ("not_verified", b.title(), None)
    # 5) known systematic noise
    if n in KNOWN_NOISE or n.isdigit():
        return ("ignore", None, "known noise / column bleed")
    # 6) everything else (stray names, team codes, CRMs) -> ignore but flag for a human
    return ("ignore", None, "UNCLASSIFIED — data bleed, review")


def sqlstr(v):
    return "null" if v is None else "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--sheet", default="Summary Report")
    ap.add_argument("--first-day-col", type=int, default=3, help="0-based col index of first date column")
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    wb = openpyxl.load_workbook(args.src, read_only=True, data_only=True)
    ws = wb[args.sheet]
    counts = collections.Counter()
    for row in ws.iter_rows(min_row=4, values_only=True):
        for cell in row[args.first_day_col:]:
            if cell is not None and str(cell).strip() != "":
                counts[str(cell).strip()] += 1
    wb.close()

    rows, bucket_tally, unclassified = [], collections.Counter(), []
    for raw, cnt in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        res = classify(raw)
        if res is None:
            continue
        bucket, canon, note = res
        bucket_tally[bucket] += 1
        if note and note.startswith("UNCLASSIFIED"):
            unclassified.append((raw, cnt))
        rows.append((norm(raw), bucket, canon, note))

    # de-dup on normalized raw_value (unique key)
    seen, dedup = set(), []
    for r in rows:
        if r[0] in seen:
            continue
        seen.add(r[0]); dedup.append(r)

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Seed: status_vocabulary (generated by tools/gen_status_vocabulary.py)\n")
        f.write(f"-- Source: {args.src}\n")
        f.write("-- Re-run the generator to refresh. Idempotent via ON CONFLICT.\n\n")
        f.write("insert into status_vocabulary (raw_value, bucket, canonical_status, note) values\n")
        lines = [f"  ({sqlstr(rv)}, '{bk}', {sqlstr(cs)}, {sqlstr(nt)})" for rv, bk, cs, nt in dedup]
        f.write(",\n".join(lines))
        f.write("\non conflict (raw_value) do update set\n"
                "  bucket = excluded.bucket,\n"
                "  canonical_status = excluded.canonical_status,\n"
                "  note = excluded.note;\n")

    print(f"Distinct day values: {len(counts)}   Seeded rows: {len(dedup)}")
    print("By bucket:", dict(bucket_tally))
    if unclassified:
        print(f"\nUNCLASSIFIED ({len(unclassified)}) — bucketed 'ignore', review these:")
        for raw, cnt in unclassified:
            print(f"   {cnt:5d}  {raw!r}")


if __name__ == "__main__":
    main()
