"""Generate the status_vocabulary seed migration from a real attendance workbook.

Reads the 'Summary Report' day-cell values, classifies each into a vocab bucket per SPEC.md §4,
and emits SQL INSERTs. Re-runnable: point --src at any period's workbook to refresh the vocabulary.

Usage:
  python tools/gen_status_vocabulary.py --src "<path to xlsx>" \
      --out supabase/migrations/20260705000003_seed_status_vocabulary.sql
"""
import argparse, sys, collections
from pathlib import Path

import openpyxl

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ingestion.status_rules import classify as _classify, normalize as norm  # noqa: E402


def classify(raw: str):
    """Return (bucket, canonical_status, note) for the seed, wrapping the shared rules."""
    n = norm(raw)
    if n == "":
        return None
    bucket, canon, is_hd = _classify(raw)
    if bucket == "unknown":
        return ("ignore", None, "UNCLASSIFIED — data bleed, review")
    if bucket == "trigger" and canon and canon.lower() not in ("absent", "no show"):
        note = "annotation: unresolved/failed"
    elif bucket == "ignore":
        note = "known noise / column bleed"
    else:
        note = "half-day" if is_hd else None
    return (bucket, canon, note)


def sqlstr(v):
    return "null" if v is None else "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--sheet", default="Summary Report")
    ap.add_argument("--first-day-col", type=int, default=3, help="0-based col index of first date column")
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    wb = openpyxl.load_workbook(args.src, read_only=True, data_only=True)
    ws = wb[args.sheet]
    counts = collections.Counter()
    for row in ws.iter_rows(min_row=4, values_only=True):
        for cell in row[args.first_day_col:]:
            if cell is not None and str(cell).strip() != "":
                counts[str(cell).strip()] += 1
    wb.close()

    rows, bucket_tally, unclassified = [], collections.Counter(), []
    for raw, cnt in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        res = classify(raw)
        if res is None:
            continue
        bucket, canon, note = res
        bucket_tally[bucket] += 1
        if note and note.startswith("UNCLASSIFIED"):
            unclassified.append((raw, cnt))
        rows.append((norm(raw), bucket, canon, note))

    # de-dup on normalized raw_value (unique key)
    seen, dedup = set(), []
    for r in rows:
        if r[0] in seen:
            continue
        seen.add(r[0]); dedup.append(r)

    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- Seed: status_vocabulary (generated by tools/gen_status_vocabulary.py)\n")
        f.write(f"-- Source: {args.src}\n")
        f.write("-- Re-run the generator to refresh. Idempotent via ON CONFLICT.\n\n")
        f.write("insert into status_vocabulary (raw_value, bucket, canonical_status, note) values\n")
        lines = [f"  ({sqlstr(rv)}, '{bk}', {sqlstr(cs)}, {sqlstr(nt)})" for rv, bk, cs, nt in dedup]
        f.write(",\n".join(lines))
        f.write("\non conflict (raw_value) do update set\n"
                "  bucket = excluded.bucket,\n"
                "  canonical_status = excluded.canonical_status,\n"
                "  note = excluded.note;\n")

    print(f"Distinct day values: {len(counts)}   Seeded rows: {len(dedup)}")
    print("By bucket:", dict(bucket_tally))
    if unclassified:
        print(f"\nUNCLASSIFIED ({len(unclassified)}) — bucketed 'ignore', review these:")
        for raw, cnt in unclassified:
            print(f"   {cnt:5d}  {raw!r}")


if __name__ == "__main__":
    main()
